language: go
go:
  - 1.16.x
dist: focal
services:
  - docker

addons:
  snaps:
    - name: helm
      confinement: classic
    - name: kubectl
      confinement: classic
    - name: yq

jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: publish-private-repose
      name: Publish to private repositories
      if: type != cron AND (type = pull_request OR branch = master)
      before_script:
        - RELEASE_VERSION=$(./hack/release-version.sh)
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip && rm awscliv2.zip
        - sudo ./aws/install
        - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${DOCKER_REPO_HOST}
      script:
        - docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -v $(pwd):/workspace
            ${DOCKER_REPO_HOST}/tech.form3/mage-targets/chart-repo:latest
            chartPublish switcheroo chart $RELEASE_VERSION
        - make docker-build
        - docker image tag switcheroo:latest ${DOCKER_REPO_HOST}/tech.form3/switcheroo:${RELEASE_VERSION}
        - docker push ${DOCKER_REPO_HOST}/tech.form3/switcheroo:${RELEASE_VERSION}

    - stage: publish
      name: Publish
      if: type != cron AND type != pull_request AND branch = master
      before_script:
        - RELEASE_VERSION=$(./hack/release-version.sh)
        - echo "Release version $RELEASE_VERSION"
      script:
        - make docker-build
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - docker image tag switcheroo:latest form3tech/switcheroo:${RELEASE_VERSION}
