language: go
go:
  - 1.16.x
dist: focal
services:
  - docker

addons:
  snaps:
    - name: helm
      confinement: classic
    - name: kubectl
      confinement: classic
    - name: yq

jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
