if: (type IN (push, cron) AND branch = master) OR (type = pull_request)
language: go
go:
  - 1.16.x
dist: focal
services:
  - docker
addons:
  snaps:
    - name: helm
      confinement: classic
    - name: kubectl
      confinement: classic
    - name: yq

jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: publish
      name: Publish
      if: type != cron
      before_script:
        - RELEASE_VERSION=$(./hack/release-version.sh)
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - echo "${AWS_CLI_SHA256_HASH}  awscliv2.zip" | shasum -a 256 -c -
        - unzip awscliv2.zip && rm awscliv2.zip
        - sudo ./aws/install
      script:
        - make docker-build


env:
  global:
    - AWS_CLI_SHA256_HASH: cc6b0541600d9d76458a107fcf2c7f7d68438e9b994f0a90ac8d6900a7b02d89
