apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
spec:
  secretName: {{ .Values.name }}-crt-secret
  dnsNames:
    - {{ .Values.name }}
    - {{ .Values.name }}.{{ .Release.Namespace }}
    - {{ .Values.name }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io