#!/usr/bin/env bash

RELEASE_BRANCH="master"
MAIN_VERSION=1.0.0

if [[ "$TRAVIS_BRANCH" == "${RELEASE_BRANCH}" && "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]]; then
    RELEASE_VERSION=$MAIN_VERSION-$TARGET_COMMIT_HASH
elif [[ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]]; then
    RELEASE_VERSION=$MAIN_VERSION-$TRAVIS_PULL_REQUEST_BRANCH-$TARGET_COMMIT_HASH
else
    RELEASE_VERSION=$MAIN_VERSION-$TRAVIS_BRANCH-$TARGET_COMMIT_HASH
fi

echo -n $RELEASE_VERSION