# issuer for cert-manager for minikube
# install cert manager: https://cert-manager.io/docs/installation/kubernetes/
# with regular manifest: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  selfSigned: {}